# Generated by Django 5.1.3 on 2026-03-04 14:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_apiuser_job_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, default=api.models.generate_api_key, help_text='The secret token sent in the Authorization: Bearer header.', max_length=67, unique=True)),
                ('label', models.CharField(blank=True, help_text="A human-readable name for this key, e.g. 'Lab Python Script'.", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Revoke a key by setting this to False.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Timestamp of the most recent authenticated request.', null=True)),
                ('user', models.ForeignKey(help_text='The API user (IP address) this key belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='api.apiuser')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
