"""
Django settings for webKinPred project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Try to import local config, fallback to defaults
try:
    from webKinPred.config_local import ALLOWED_FRONTEND_IPS, DEBUG
except ImportError:
    ALLOWED_FRONTEND_IPS = ["127.0.0.1", "localhost"]
    DEBUG = True

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is required.")

DEBUG = DEBUG
ALLOWED_FRONTEND_IPS = ALLOWED_FRONTEND_IPS

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "api.apps.ApiConfig",
    "db_models",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "api.observability.middleware.RequestIDMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Docker-aware CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://kineticxpredictor.humanmetabolism.org",
    "https://predictor.openkinetics.org",
    "https://www.kineticxpredictor.humanmetabolism.org",
    "https://www.predictor.openkinetics.org",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://kineticxpredictor.humanmetabolism.org",
    "https://predictor.openkinetics.org",
    "https://www.kineticxpredictor.humanmetabolism.org",
    "https://www.predictor.openkinetics.org",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Docker-aware allowed hosts
ALLOWED_HOSTS = [
    "kineticxpredictor.humanmetabolism.org",
    "127.0.0.1",
    "localhost",
    "backend",  # Docker service name
    "0.0.0.0",
]

ROOT_URLCONF = "webKinPred.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "webKinPred.wsgi.application"

# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    },
    "seqmap": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "media/sequence_info/seqmap.sqlite3",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DATABASE_ROUTERS = ["api.dbrouters.SeqMapRouter"]

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/django_static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Redis URL based on environment
REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6380/0")

# Extract Redis host and port for different configurations
if "redis://" in REDIS_URL:
    redis_parts = REDIS_URL.replace("redis://", "").split("/")
    redis_host_port = redis_parts[0]
    if ":" in redis_host_port:
        redis_host, redis_port = redis_host_port.split(":")
    else:
        redis_host = redis_host_port
        redis_port = "6379"
else:
    redis_host = "localhost"
    redis_port = "6380"

# Celery settings
CELERY_BROKER_URL = f"redis://{redis_host}:{redis_port}/0"
CELERY_RESULT_BACKEND = f"redis://{redis_host}:{redis_port}/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_TASK_TRACK_STARTED = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False
CELERY_WORKER_REDIRECT_STDOUTS = False

# Cache settings
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{redis_host}:{redis_port}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": None,
    }
}

LOGGING_REDIS_URL = f"redis://{redis_host}:{redis_port}/2"


def _log_level(name: str, default: str) -> str:
    return os.environ.get(name, default).upper()


LOG_LEVEL = _log_level("LOG_LEVEL", "INFO")
DJANGO_LOG_LEVEL = _log_level("DJANGO_LOG_LEVEL", LOG_LEVEL)
CELERY_LOG_LEVEL = _log_level("CELERY_LOG_LEVEL", LOG_LEVEL)
SUBPROCESS_LOG_LEVEL = _log_level("SUBPROCESS_LOG_LEVEL", LOG_LEVEL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "correlation": {
            "()": "api.observability.formatters.CorrelationFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "api.observability.formatters.JsonLogFormatter",
            "format": "%(timestamp)s %(level)s %(logger)s %(message)s %(service)s "
            "%(request_id)s %(job_public_id)s %(celery_task_id)s %(method_key)s %(target)s "
            "%(event)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["correlation"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "api": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "api.prediction_engines.subprocess_runner": {
            "handlers": ["console"],
            "level": SUBPROCESS_LOG_LEVEL,
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": CELERY_LOG_LEVEL,
            "propagate": False,
        },
        "django": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "gunicorn.access": {
            "handlers": ["console"],
            "level": os.environ.get("GUNICORN_ACCESS_LOG_LEVEL", "WARNING").upper(),
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "urllib3": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}
